sources:
  - RadioCanadaDisplay.glyphs
  - RadioCanadaDisplay-Italic.glyphs
axisOrder:
  - wght
familyName: "Radio Canada Display"
buildStatic: true
buildOTF: false
buildWebfont: false
stat:
  RadioCanadaDisplay[wght].ttf:
  - name: Weight
    tag: wght
    values:
    - name: Regular
      value: 400
      linkedValue: 700
      flags: 2
    - name: Medium
      value: 500
    - name: SemiBold
      value: 600
    - name: Bold
      value: 700
  - name: Italic
    tag: ital
    values:
    - name: Roman
      value: 0
      linkedValue: 1
      flags: 2
  RadioCanadaDisplay-Italic[wght].ttf:
  - name: Weight
    tag: wght
    values:
    - name: Regular
      value: 400
      linkedValue: 700
      flags: 2
    - name: Medium
      value: 500
    - name: SemiBold
      value: 600
    - name: Bold
      value: 700
  - name: Italic
    tag: ital
    values:
    - name: Italic
      value: 1
